### ISSUE TITLE
Create a default SSL certificate for Ubiquity Image on startup

### ISSUE THREAD

**Issue by ranhrl** [IBM/ubiquity#123]
Create a default SSL root key and signed certificate (and key) to be used by the ubiquity server in case the customer did not provide one.

**Comment by shay-berman** [comment]
@ranhrl  I conducted code review -> https://reviewable.io/reviews/ibm/ubiquity/124#-KvMO04rrW7ajXizb5bx

Please review and apply some changes according before merge
