### ISSUE TITLE
Spectrum-Scale backend changes for Docker managed plugin

### ISSUE THREAD

**Issue by aswarke** [IBM/ubiquity#125]
Make the following changes to spectrum-scale backend in order for it to work with Docker's Managed plugin system

1) Updating spectrum-scale SSH connector and adding methods for managing Lightweight volumes. Using ssh identity file to login in SSH connector

2) Updating Dockerfile with addition of openssh package to enable SSH connector within ubiquity container

3) Updating spectrum-scale mounter to use symlinks when incoming requests are from Docker engine

**Comment by shay-berman** [comment]
irrelevancy
will keep the swarm PRs a bit longer.
