### ISSUE TITLE
SCBE changes for Docker Managed plugin system

### ISSUE THREAD

**Issue by aswarke** [IBM/ubiquity#127]
Changes needed within SCBE backend code if any, Dockerfile, etc to enable SCBE backend, including iscsi and multipathing) within Ubiquity-Docker-Plugin v2 plugin .

**Comment by shay-berman** [comment]
Since Docker Swarm support in Ubiquity was set to low priority, I will close this ticket. When even we decide to support Docker Swarm, we will open relevant tickets to implement it.
