### ISSUE TITLE
Add host notion to the Attach\Detach interfaces

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity#23]
- Attach 
The Attach interface([HERE](https://github.com/IBM/ubiquity/blob/master/remote/client.go#L153)) must get the hostname for attachment as an argument.

- Detach
The same for detach

**Comment by midoblgsm** [comment]
The attach interface will get an AttachRequest object that contains as one of the attributes the hostname. Same thing for the detach.

**Comment by shay-berman** [comment]
@midoblgsm, please provide estimation when this ticket will be finished?
thanks
