### ISSUE TITLE
Add size unit to the size option given by user

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity#37]
Current state : currently the size value is gb number (without mention the size unit).
Wanted state : size should followed with size unit (e.g 10gb)

example : 
docker volume create --driver=ubiquity --name my_first_A9000_vol --opt size=10gb --opt profile=gold

**Comment by shay-berman** [comment]
**Two important comments that need to be apply as part of this ticket :** 
1. The default size unit should be GB. for example if customer runs size=1 it means 1GB. of cause the customer can specific the unit suffix as well, but if he don't then its GB.

2. The minimal allocation unit should be 1MB for SCBE backend, and it should round up to this minimal allocation unit. For example : if customer request 1.5 megabyte(1572864Bytes) it should round it to 2MB.


Next time i should put all of this in the ticket description in the beginning.

**Comment by liortamari** [comment]
There is no need for "minimal allocation unit"
SCB should decide the allocation size

**Comment by shay-berman** [comment]
closing this ticket, since its not relevant for k8s side of thing.
Opened internal ticket for future use.
