### ISSUE TITLE
Implement Unit test cases for Spectrum Scale REST connector using ginkgo

### ISSUE THREAD

**Issue by yadaven** [IBM/ubiquity#42]
Implement Unit test cases for REST connector using http mockups. 

Currently I have implemented the test cases for all interfaces. Total number of test case ~ 55. Below is one example for Unit test case.

      Context(".GetClusterID",func() {
                It("Should Pass and Cluster ID should be valid",func() {
                        getClusterRespo := connectors.GetClusterResponse{}
                        getClusterRespo.Status.Code = 200
                        getClusterRespo.Status.Message = "passed to get cluster id"
                        getClusterRespo.Cluster.ClusterSummary.ClusterID = 12345
                        marshalledResponse, err := json.Marshal(getClusterRespo)
                        Expect(err).ToNot(HaveOccurred())
                        registerurl := fakeurl+"/scalemgmt/v2/cluster"
                        httpmock.RegisterResponder(
                                "GET",
                                 registerurl,
                                 httpmock.NewStringResponder(200,string(marshalledResponse)),
                        )
                        str,err := spectrumRestV2.GetClusterId()
                        Expect(str).To(Equal("12345"))
                })

Added new function NewspectrumRestV2WithClient which will return pointer to httpClient. This pointer we will use to activate the mockup as below

                spectrumRestV2, client,err = connectors.NewspectrumRestV2WithClient(logger, restConfig)
                Expect(err).ToNot(HaveOccurred())
                httpmock.ActivateNonDefault(client)

**Comment by shay-berman** [comment]
@yadaven  is this issue still relevant? do we need it open?

**Comment by shay-berman** [comment]
@yadaven is this issue still relevant? do we need it open?

**Comment by yadaven** [comment]
Unit test cases have already been added for REST connector. So closing it.
