### ISSUE TITLE
Configurable debug level (server and plugins)

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity#49]
- Add new param to the config file called DebugMode as bool (the param should be in the generic level of the config file)
- if true then log level is Debug else its Info level.  (if not configured then default is Info level, means true)

- make sure it works for the server and the plugins (add initialization for the logger in k8s provisioner + flexvol ).

- In addition please add debug to all the execute commands (please log output, error and exitcode to debug level)

**Comment by liortamari** [comment]
added to conf
logLevel = "info"         # debug / info / error
default is "info"
