### ISSUE TITLE
Revisit README file to conclude block and file notion

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity#53]
We need to make the README file unify for block and file, because currently its only focus on spectrum scale.

@aswarke  suggested to put all the backend specific configurations inside different md file and point it in the main README file. So there will be ibm-spectrum-scale.md and ibm-block-storage-via-scbe.md.

So on this ticket @aswarke  should work on SSc md file and also to clean up the current README file, and I will work on the block md file and also review all the md files with Dima to be align with IBM standard.

This ticket should be done on branch [update_READMEs_for_unify_block_and_file] and at the end we need to merge it into dev branch when we all approve the docs.

**Comment by shay-berman** [comment]
@aswarke  I assign this ticket to you, so please work on it today and tomorrow (before 4july )
Thanks a lot. A similar ticket will be opened on each branch.

**Comment by aswarke** [comment]
@shay-berman assigning this to you, created separate md files for each storage backend . Please add content in ibm-block-storage-via-scbe.md for scbe and review commits
