### ISSUE TITLE
docker plugin attach not work if no iscsi package installed on FC node

### ISSUE THREAD

**Issue by YuDaiWang** [IBM/ubiquity#56]
I am testing the acceptance test case on a docker node through FC. There is no iscsi package installed on this node.
when running command "docker run -t -i -d --name test11 --volume-driver ubiquity --volume test1Vol:/data --entrypoint /bin/sh alpine", get an error:
<img width="1262" alt="error" src="https://user-images.githubusercontent.com/28969890/27578471-c56dbe0a-5b56-11e7-80d3-59095b229fbb.png">

**Comment by liortamari** [comment]
i reverted the fix because it was only workaround for the release
