### ISSUE TITLE
Security-Requirement sudoers

### ISSUE THREAD

**Issue by ps20renar** [IBM/ubiquity#71]
Hallo All,
during the Evaluation of ubiquity we see following config request at systemd of the ubiguity Services, this is too weak if we apply the security rules here. The recommendation of the config mentioned:

For non-root users, such as USER, configure the sudoers as follows:
    USER ALL= NOPASSWD: /usr/bin/, /bin/
    Defaults:%USER !requiretty
    Defaults:%USER secure_path = /sbin:/bin:/usr/sbin:/usr/bin

But this generate for the non-root user a complete root execution rights??
In the start logs of systemd Output we see following:
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de systemd[1]: Started ubiquity docker plugin Service.
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de systemd[1]: Starting ubiquity docker plugin Service...
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de ubiquity-docker-plugin[29127]: Starting ubiquity plugin with /etc/ubiquity/ubiquity-clien...file
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de sudo[29134]: svcdo-ubi01 : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/touch /etc/do...y.json
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de sudo[29140]: svcdo-ubi01 : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/chmod -R **777** ...ocker/
Jul 07 09:47:50 sbdl7001.t7.lan.tuhuk.de sudo[29154]: svcdo-ubi01 : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/chown 9999:99...y.json

Are These steps the final implementation?

**Comment by heikoludwig** [comment]
Hi, this is definitely not a solution we can sustain in an enterprise. We are currently looking into just limiting  it to what is really necessary. Getting back on this shortly.

**Comment by shay-berman** [comment]
@aswarke  can we close this issue?
Since the ubiquity v1+ is no longer uses sudo, because its fully dockerized.
Any reason to keep this issue open?

**Comment by ps20renar** [comment]
Hallo All,
this issue can be closed.
Regards Renar

**Comment by heikoludwig** [comment]
Thanks, Renar,
 
Heiko
 
-----Heiko Ludwig, Dr. rer. pol., Mgr. Ubiquitous PlatformsIBM Almaden Research Center, 650 Harry Road, San Jose, CA 95120-6099hludwig@us.ibm.com, tel. +1 408-927-1488, mob. +1 646-675-8469http://researcher.ibm.com/researcher/view.php?person=us-hludwig
 
 
----- Original message -----From: ps20renar <notifications@github.com>To: IBM/ubiquity <ubiquity@noreply.github.com>Cc: heikoludwig <hludwig@us.ibm.com>, Comment <comment@noreply.github.com>Subject: Re: [IBM/ubiquity] Security-Requirement sudoers (#71)Date: Thu, Apr 5, 2018 7:42 AM 
Hallo All,this issue can be closed.Regards Renar

**Comment by shay-berman** [comment]
@yadaven  I would like to close this old ticket. since its not relevant any more. please approve.

**Comment by yadaven** [comment]
Yes we can close it. Approved
