### ISSUE TITLE
re:Seem to accept any command

### ISSUE THREAD

**Issue by macthev** [IBM/ubiquity#82]
Server allows the following from ubiquity-docker-plugin:
ClientConfig = '"192.168.0.2 (Access_Type=RW,Protocols=3)"&& id >/tmp/id.out'

**Comment by shay-berman** [comment]
@aswarke is this issue still relevant?  if so who from scale is handling it?

**Comment by shay-berman** [comment]
@yadaven  can i close this? i think its not relevant.

**Comment by yadaven** [comment]
We are not supporting NFS backend at present. So we can close it
