### ISSUE TITLE
Make init call do not use DB.

### ISSUE THREAD

**Issue by midoblgsm** [IBM/ubiquity#96]
For the next step of changing from sqlite to postgresql, we need to make sure that init calls do not try to connect to the DB because this might fail when postgres is not yet ready.
- SCBE no op since activate does not do anything
- SSc change code of activate to avoid touching the DB

**Comment by shay-berman** [comment]
@midoblgsm  is this ticket still relevant? is it only for SSc (if so please label it for SSc).

**Comment by shay-berman** [comment]
@aswarke   @yadaven   is this issue relevant?

**Comment by shay-berman** [comment]
The scale milestone will address this issue in different way.
@yadaven  please approve we can close this issue.

**Comment by yadaven** [comment]
In activate call Scale mainly calls below api related to DB

s.dataModel.SetClusterId(clusterId)

SetClusterId just updates in-memory struct and does not do any DB related operations. So this ticket is not relevant. So closing it.
